config_version = "0"

exclude_patterns = []

[smells]
mode = "disabled"

[[source]]
name = "default"
default = true

[[plugin]]
name = "markdownlint"
mode = "comment"

[[plugin]]
name = "prettier"

[[plugin]]
name = "trufflehog"

[[ignore]]
file_patterns = ["LICENSE.md"]
rules = ["markdownlint:MD041"]